"""fix user table name

Revision ID: 5607c828d37f
Revises: 3d35dcd30116
Create Date: 2025-08-21 18:50:15.898989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import dataline

# revision identifiers, used by Alembic.
revision: str = '5607c828d37f'
down_revision: Union[str, None] = '3d35dcd30116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glossary', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('unique_value_dict', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', dataline.models.base.CustomUUIDType(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_conversations_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_positive', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('avatar_blob', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('config')
        batch_op.drop_column('email')
        batch_op.drop_column('avatar_blob')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('role')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('is_positive')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversations_user_id_user'), type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_column('config')
        batch_op.drop_column('unique_value_dict')
        batch_op.drop_column('glossary')

    # ### end Alembic commands ###
