name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3 AM UTC (adjust as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork's default branch
        uses: actions/checkout@v4
        with:
          ref: main  # or main

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/RamiAwar/dataline.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/main --allow-unrelated-histories || echo "No changes to merge"

      - name: Push changes to your fork
        run: git push origin main

